BEGIN;

CREATE TYPE "ExpenseCategory_new" AS ENUM (
  'FUEL',
  'ELECTRICITY',
  'INTERNET',
  'SECURITY_FEE',
  'AUDIT_AND_ACCOUNTANCY',
  'REPAIRS_AND_MAINTENANCE',
  'VEHICLE_REGISTRATION',
  'VEHICLE_PARTICULARS',
  'MEDICALS',
  'VEHICLE_HIRE',
  'AIRPORT_TICKETS_TOLLS',
  'STATIONERIES',
  'TOILETRIES',
  'CAPITAL_EXPENDITURE',
  'INSURANCE',
  'OFFICE_EQUIPMENT',
  'STAFF_SALARY',
  'LICENSE_AND_LEVIES',
  'BANK_CHARGES',
  'TRANSPORT_AND_TRAVELING',
  'ACCOMMODATION_AND_FEEDING',
  'TELEPHONE_AND_POSTAGES',
  'RENT',
  'FURNITURE_AND_FITTING',
  'CONSULTANCY',
  'ADVERTISEMENT_AND_SIGNAGE'
);

ALTER TABLE "Expense"
  ALTER COLUMN "expenseCategory" TYPE TEXT USING "expenseCategory"::text;

ALTER TABLE "Budget"
  ALTER COLUMN "expenseCategory" TYPE TEXT USING "expenseCategory"::text;

UPDATE "Expense"
SET "expenseCategory" = CASE
  WHEN "expenseCategory" IN ('FUEL') THEN 'FUEL'
  WHEN "expenseCategory" IN ('ELECTRICITY', 'UTILITIES', 'WATER') THEN 'ELECTRICITY'
  WHEN "expenseCategory" IN ('INTERNET') THEN 'INTERNET'
  WHEN "expenseCategory" IN (
    'SECURITY_FEE', 'SECURITY', 'UNIFORMS', 'SECURITY_GEAR', 'GUARD_EQUIPMENT',
    'CCTV_CAMERAS', 'CCTV_INSTALLATION', 'CCTV_MAINTENANCE', 'ALARM_SYSTEMS',
    'ACCESS_CONTROL', 'SMART_HOME_DEVICES', 'COMMUNICATION_EQUIPMENT', 'RADIOS',
    'BODY_CAMERAS', 'PATROL_VEHICLES', 'SITE_SECURITY', 'SAFETY_GEAR', 'HELMETS',
    'BOOTS', 'VESTS', 'GLOVES', 'CLEANING', 'WASTE_DISPOSAL', 'WASTE_REMOVAL'
  ) THEN 'SECURITY_FEE'
  WHEN "expenseCategory" IN ('AUDIT_AND_ACCOUNTANCY', 'ACCOUNTING_FEES', 'AUDIT_FEES') THEN 'AUDIT_AND_ACCOUNTANCY'
  WHEN "expenseCategory" IN (
    'REPAIRS_AND_MAINTENANCE', 'MAINTENANCE', 'REPAIRS', 'TYRES', 'VEHICLE_INSPECTION',
    'OIL_CHANGE', 'BRAKE_PADS', 'BATTERY', 'LIGHTS', 'WIPERS', 'CAR_WASH', 'DETAILING'
  ) THEN 'REPAIRS_AND_MAINTENANCE'
  WHEN "expenseCategory" IN ('VEHICLE_REGISTRATION') THEN 'VEHICLE_REGISTRATION'
  WHEN "expenseCategory" IN ('VEHICLE_PARTICULARS') THEN 'VEHICLE_PARTICULARS'
  WHEN "expenseCategory" IN ('MEDICALS') THEN 'MEDICALS'
  WHEN "expenseCategory" IN ('VEHICLE_HIRE') THEN 'VEHICLE_HIRE'
  WHEN "expenseCategory" IN ('AIRPORT_TICKETS_TOLLS', 'ROAD_TOLLS', 'AIRFARE', 'TOLLS_TRAVEL') THEN 'AIRPORT_TICKETS_TOLLS'
  WHEN "expenseCategory" IN ('STATIONERIES', 'STATIONERY', 'OFFICE_SUPPLIES', 'PRINTING') THEN 'STATIONERIES'
  WHEN "expenseCategory" IN ('TOILETRIES') THEN 'TOILETRIES'
  WHEN "expenseCategory" IN (
    'CAPITAL_EXPENDITURE', 'VEHICLE_PURCHASE', 'VEHICLE_IMPORT', 'VEHICLE_CUSTOMS',
    'EQUIPMENT', 'MACHINERY', 'TOOLS', 'COMPUTER', 'LAPTOP', 'PRINTER', 'SCANNER',
    'SOFTWARE', 'SUBSCRIPTION', 'RENOVATION', 'CONSTRUCTION', 'BUILDING', 'LAND',
    'CONSTRUCTION_MATERIALS', 'CEMENT', 'SAND', 'GRAVEL', 'GRANITE', 'BLOCKS', 'BRICKS',
    'TIMBER', 'STEEL', 'REINFORCEMENT', 'NAILS', 'SCREWS', 'PAINT', 'TILES', 'ROOFING',
    'PLUMBING_MATERIALS', 'ELECTRICAL_MATERIALS', 'WIRES', 'CONDUITS', 'FITTINGS',
    'FIXTURES', 'DOORS', 'WINDOWS', 'HARDWARE', 'TOOLS_CONSTRUCTION', 'EQUIPMENT_RENTAL',
    'CRANE', 'EXCAVATOR', 'CONCRETE_MIXER', 'GENERATOR', 'SUBCONTRACTORS', 'LABOR',
    'SKILLED_LABOR', 'UNSKILLED_LABOR'
  ) THEN 'CAPITAL_EXPENDITURE'
  WHEN "expenseCategory" IN ('INSURANCE', 'INSURANCE_ADMIN') THEN 'INSURANCE'
  WHEN "expenseCategory" IN ('OFFICE_EQUIPMENT') THEN 'OFFICE_EQUIPMENT'
  WHEN "expenseCategory" IN ('STAFF_SALARY', 'SALARIES', 'WAGES', 'BONUSES', 'COMMISSIONS', 'STAFF_BENEFITS', 'PENSION') THEN 'STAFF_SALARY'
  WHEN "expenseCategory" IN ('LICENSE_AND_LEVIES', 'LICENSE', 'PERMITS', 'BUILDING_PERMITS', 'ENVIRONMENTAL_PERMITS', 'SECURITY_LICENSES', 'SECURITY_PERMITS', 'VISA', 'PASSPORT') THEN 'LICENSE_AND_LEVIES'
  WHEN "expenseCategory" IN ('BANK_CHARGES', 'INTEREST') THEN 'BANK_CHARGES'
  WHEN "expenseCategory" IN ('TRANSPORT_AND_TRAVELING', 'PARKING', 'DRIVER_ALLOWANCE', 'LOCAL_TRAVEL', 'INTERNATIONAL_TRAVEL', 'TRANSPORTATION', 'TAXI', 'RENTAL_CAR', 'FUEL_TRAVEL', 'PARKING_TRAVEL') THEN 'TRANSPORT_AND_TRAVELING'
  WHEN "expenseCategory" IN ('ACCOMMODATION_AND_FEEDING', 'HOTEL', 'MEALS', 'SUBSISTENCE', 'STAFF_PARTY', 'TEAM_BUILDING', 'CLIENT_ENTERTAINMENT', 'STAFF_ENTERTAINMENT', 'ENTERTAINMENT') THEN 'ACCOMMODATION_AND_FEEDING'
  WHEN "expenseCategory" IN ('TELEPHONE_AND_POSTAGES', 'TELEPHONE', 'POSTAGE', 'COURIER') THEN 'TELEPHONE_AND_POSTAGES'
  WHEN "expenseCategory" IN ('RENT') THEN 'RENT'
  WHEN "expenseCategory" IN ('FURNITURE_AND_FITTING', 'FURNITURE') THEN 'FURNITURE_AND_FITTING'
  WHEN "expenseCategory" IN (
    'CONSULTANCY', 'LEGAL_FEES', 'CONSULTING_FEES', 'TRAINING', 'RECRUITMENT',
    'SECURITY_CONSULTING', 'RISK_ASSESSMENT', 'SECURITY_AUDIT', 'GUARD_TRAINING',
    'DONATIONS', 'CHARITY', 'GIFTS', 'PETTY_CASH', 'CONTINGENCY', 'MISCELLANEOUS', 'OTHER'
  ) THEN 'CONSULTANCY'
  WHEN "expenseCategory" IN (
    'ADVERTISEMENT_AND_SIGNAGE', 'ADVERTISING', 'DIGITAL_MARKETING', 'SOCIAL_MEDIA_ADS',
    'PRINT_ADS', 'BILLBOARDS', 'RADIO_ADS', 'TV_ADS', 'PROMOTIONS', 'DISCOUNTS',
    'WEBSITE', 'SEO', 'CONTENT_CREATION', 'BRANDING', 'EVENT_SPONSORSHIP', 'TRADE_SHOWS',
    'MARKETING_MATERIALS', 'BROCHURES', 'FLYERS', 'BUSINESS_CARDS'
  ) THEN 'ADVERTISEMENT_AND_SIGNAGE'
  ELSE 'CONSULTANCY'
END;

UPDATE "Budget"
SET "expenseCategory" = CASE
  WHEN "expenseCategory" IS NULL THEN NULL
  WHEN "expenseCategory" IN ('FUEL') THEN 'FUEL'
  WHEN "expenseCategory" IN ('ELECTRICITY', 'UTILITIES', 'WATER') THEN 'ELECTRICITY'
  WHEN "expenseCategory" IN ('INTERNET') THEN 'INTERNET'
  WHEN "expenseCategory" IN (
    'SECURITY_FEE', 'SECURITY', 'UNIFORMS', 'SECURITY_GEAR', 'GUARD_EQUIPMENT',
    'CCTV_CAMERAS', 'CCTV_INSTALLATION', 'CCTV_MAINTENANCE', 'ALARM_SYSTEMS',
    'ACCESS_CONTROL', 'SMART_HOME_DEVICES', 'COMMUNICATION_EQUIPMENT', 'RADIOS',
    'BODY_CAMERAS', 'PATROL_VEHICLES', 'SITE_SECURITY', 'SAFETY_GEAR', 'HELMETS',
    'BOOTS', 'VESTS', 'GLOVES', 'CLEANING', 'WASTE_DISPOSAL', 'WASTE_REMOVAL'
  ) THEN 'SECURITY_FEE'
  WHEN "expenseCategory" IN ('AUDIT_AND_ACCOUNTANCY', 'ACCOUNTING_FEES', 'AUDIT_FEES') THEN 'AUDIT_AND_ACCOUNTANCY'
  WHEN "expenseCategory" IN (
    'REPAIRS_AND_MAINTENANCE', 'MAINTENANCE', 'REPAIRS', 'TYRES', 'VEHICLE_INSPECTION',
    'OIL_CHANGE', 'BRAKE_PADS', 'BATTERY', 'LIGHTS', 'WIPERS', 'CAR_WASH', 'DETAILING'
  ) THEN 'REPAIRS_AND_MAINTENANCE'
  WHEN "expenseCategory" IN ('VEHICLE_REGISTRATION') THEN 'VEHICLE_REGISTRATION'
  WHEN "expenseCategory" IN ('VEHICLE_PARTICULARS') THEN 'VEHICLE_PARTICULARS'
  WHEN "expenseCategory" IN ('MEDICALS') THEN 'MEDICALS'
  WHEN "expenseCategory" IN ('VEHICLE_HIRE') THEN 'VEHICLE_HIRE'
  WHEN "expenseCategory" IN ('AIRPORT_TICKETS_TOLLS', 'ROAD_TOLLS', 'AIRFARE', 'TOLLS_TRAVEL') THEN 'AIRPORT_TICKETS_TOLLS'
  WHEN "expenseCategory" IN ('STATIONERIES', 'STATIONERY', 'OFFICE_SUPPLIES', 'PRINTING') THEN 'STATIONERIES'
  WHEN "expenseCategory" IN ('TOILETRIES') THEN 'TOILETRIES'
  WHEN "expenseCategory" IN (
    'CAPITAL_EXPENDITURE', 'VEHICLE_PURCHASE', 'VEHICLE_IMPORT', 'VEHICLE_CUSTOMS',
    'EQUIPMENT', 'MACHINERY', 'TOOLS', 'COMPUTER', 'LAPTOP', 'PRINTER', 'SCANNER',
    'SOFTWARE', 'SUBSCRIPTION', 'RENOVATION', 'CONSTRUCTION', 'BUILDING', 'LAND',
    'CONSTRUCTION_MATERIALS', 'CEMENT', 'SAND', 'GRAVEL', 'GRANITE', 'BLOCKS', 'BRICKS',
    'TIMBER', 'STEEL', 'REINFORCEMENT', 'NAILS', 'SCREWS', 'PAINT', 'TILES', 'ROOFING',
    'PLUMBING_MATERIALS', 'ELECTRICAL_MATERIALS', 'WIRES', 'CONDUITS', 'FITTINGS',
    'FIXTURES', 'DOORS', 'WINDOWS', 'HARDWARE', 'TOOLS_CONSTRUCTION', 'EQUIPMENT_RENTAL',
    'CRANE', 'EXCAVATOR', 'CONCRETE_MIXER', 'GENERATOR', 'SUBCONTRACTORS', 'LABOR',
    'SKILLED_LABOR', 'UNSKILLED_LABOR'
  ) THEN 'CAPITAL_EXPENDITURE'
  WHEN "expenseCategory" IN ('INSURANCE', 'INSURANCE_ADMIN') THEN 'INSURANCE'
  WHEN "expenseCategory" IN ('OFFICE_EQUIPMENT') THEN 'OFFICE_EQUIPMENT'
  WHEN "expenseCategory" IN ('STAFF_SALARY', 'SALARIES', 'WAGES', 'BONUSES', 'COMMISSIONS', 'STAFF_BENEFITS', 'PENSION') THEN 'STAFF_SALARY'
  WHEN "expenseCategory" IN ('LICENSE_AND_LEVIES', 'LICENSE', 'PERMITS', 'BUILDING_PERMITS', 'ENVIRONMENTAL_PERMITS', 'SECURITY_LICENSES', 'SECURITY_PERMITS', 'VISA', 'PASSPORT') THEN 'LICENSE_AND_LEVIES'
  WHEN "expenseCategory" IN ('BANK_CHARGES', 'INTEREST') THEN 'BANK_CHARGES'
  WHEN "expenseCategory" IN ('TRANSPORT_AND_TRAVELING', 'PARKING', 'DRIVER_ALLOWANCE', 'LOCAL_TRAVEL', 'INTERNATIONAL_TRAVEL', 'TRANSPORTATION', 'TAXI', 'RENTAL_CAR', 'FUEL_TRAVEL', 'PARKING_TRAVEL') THEN 'TRANSPORT_AND_TRAVELING'
  WHEN "expenseCategory" IN ('ACCOMMODATION_AND_FEEDING', 'HOTEL', 'MEALS', 'SUBSISTENCE', 'STAFF_PARTY', 'TEAM_BUILDING', 'CLIENT_ENTERTAINMENT', 'STAFF_ENTERTAINMENT', 'ENTERTAINMENT') THEN 'ACCOMMODATION_AND_FEEDING'
  WHEN "expenseCategory" IN ('TELEPHONE_AND_POSTAGES', 'TELEPHONE', 'POSTAGE', 'COURIER') THEN 'TELEPHONE_AND_POSTAGES'
  WHEN "expenseCategory" IN ('RENT') THEN 'RENT'
  WHEN "expenseCategory" IN ('FURNITURE_AND_FITTING', 'FURNITURE') THEN 'FURNITURE_AND_FITTING'
  WHEN "expenseCategory" IN (
    'CONSULTANCY', 'LEGAL_FEES', 'CONSULTING_FEES', 'TRAINING', 'RECRUITMENT',
    'SECURITY_CONSULTING', 'RISK_ASSESSMENT', 'SECURITY_AUDIT', 'GUARD_TRAINING',
    'DONATIONS', 'CHARITY', 'GIFTS', 'PETTY_CASH', 'CONTINGENCY', 'MISCELLANEOUS', 'OTHER'
  ) THEN 'CONSULTANCY'
  WHEN "expenseCategory" IN (
    'ADVERTISEMENT_AND_SIGNAGE', 'ADVERTISING', 'DIGITAL_MARKETING', 'SOCIAL_MEDIA_ADS',
    'PRINT_ADS', 'BILLBOARDS', 'RADIO_ADS', 'TV_ADS', 'PROMOTIONS', 'DISCOUNTS',
    'WEBSITE', 'SEO', 'CONTENT_CREATION', 'BRANDING', 'EVENT_SPONSORSHIP', 'TRADE_SHOWS',
    'MARKETING_MATERIALS', 'BROCHURES', 'FLYERS', 'BUSINESS_CARDS'
  ) THEN 'ADVERTISEMENT_AND_SIGNAGE'
  ELSE 'CONSULTANCY'
END;

ALTER TABLE "Expense"
  ALTER COLUMN "expenseCategory" TYPE "ExpenseCategory_new"
  USING "expenseCategory"::"ExpenseCategory_new";

ALTER TABLE "Budget"
  ALTER COLUMN "expenseCategory" TYPE "ExpenseCategory_new"
  USING CASE
    WHEN "expenseCategory" IS NULL THEN NULL
    ELSE "expenseCategory"::"ExpenseCategory_new"
  END;

ALTER TYPE "ExpenseCategory" RENAME TO "ExpenseCategory_old";
ALTER TYPE "ExpenseCategory_new" RENAME TO "ExpenseCategory";
DROP TYPE "ExpenseCategory_old";

COMMIT;