export const COLLAPSED_EXPENSE_CATEGORIES = [
  'ELECTRICITY',
  'INTERNET',
  'SECURITY_FEE',
  'AUDIT_AND_ACCOUNTANCY',
  'REPAIRS_AND_MAINTENANCE',
  'VEHICLE_REGISTRATION',
  'VEHICLE_PARTICULARS',
  'MEDICALS',
  'VEHICLE_HIRE',
  'AIRPORT_TICKETS_TOLLS',
  'STATIONERIES',
  'TOILETRIES',
  'CAPITAL_EXPENDITURE',
  'INSURANCE',
  'OFFICE_EQUIPMENT',
  'STAFF_SALARY',
  'LICENSE_AND_LEVIES',
  'BANK_CHARGES',
  'TRANSPORT_AND_TRAVELING',
  'ACCOMMODATION_AND_FEEDING',
  'TELEPHONE_AND_POSTAGES',
  'RENT',
  'FUEL',
  'FURNITURE_AND_FITTING',
  'CONSULTANCY',
  'ADVERTISEMENT_AND_SIGNAGE',
];

export const DEFAULT_EXPENSE_TYPE = 'ADMINISTRATIVE';

export const EXPENSE_TYPE_OPTIONS = [
  'OPERATIONAL',
  'ADMINISTRATIVE',
  'MARKETING',
  'CAPITAL',
  'SECURITY_SERVICES',
  'CONSTRUCTION',
  'OTHER',
];

export const EXPENSE_CATEGORIES_BY_TYPE = Object.fromEntries(
  EXPENSE_TYPE_OPTIONS.map((type) => [type, COLLAPSED_EXPENSE_CATEGORIES])
);

export const VEHICLE_RELATED_EXPENSE_CATEGORIES = new Set([
  'FUEL',
  'INSURANCE',
  'VEHICLE_REGISTRATION',
  'VEHICLE_PARTICULARS',
  'VEHICLE_HIRE',
]);